[[news]]
date = "2026-02"
content = "We released [DeepImageSearch](https://arxiv.org/abs/2602.10809), defining a new paradigm for image retrieval."

[[news]]
date = "2025-09"
content = "1 paper accepted to NeurIPS 2025 ðŸŽ‰ Thanks to all collaborators!"

[[news]]
date = "2025-07"
content = "2 papers accepted to ACL 2025, including 1 Oral ðŸŽ‰ Thanks to all collaborators!"

[[news]]
date = "2024-09"
content = "4 papers accepted to EMNLP 2024 ðŸŽ‰ Thanks to all collaborators!"
